# Generated by Django 5.0 on 2025-01-01 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0028_alter_submission_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchassistant',
            name='can_acquire_funding',
            field=models.BooleanField(default=False, help_text='Permission to work on funding acquisition'),
        ),
        migrations.AddField(
            model_name='researchassistant',
            name='can_approach_participants',
            field=models.BooleanField(default=False, help_text='Permission to approach potential participants'),
        ),
        migrations.AddField(
            model_name='researchassistant',
            name='can_collect_data',
            field=models.BooleanField(default=False, help_text='Permission to collect research data'),
        ),
        migrations.AddField(
            model_name='researchassistant',
            name='can_conceptualize_methodology',
            field=models.BooleanField(default=False, help_text='Permission to work on conceptualization and methodology'),
        ),
        migrations.AddField(
            model_name='researchassistant',
            name='can_consent_participants',
            field=models.BooleanField(default=False, help_text='Permission to consent and interact with potential participants'),
        ),
        migrations.AddField(
            model_name='researchassistant',
            name='can_identify_participants',
            field=models.BooleanField(default=False, help_text='Permission to identify potential participants'),
        ),
        migrations.AddField(
            model_name='researchassistant',
            name='can_validate_analyze_data',
            field=models.BooleanField(default=False, help_text='Permission to validate and analyze data'),
        ),
    ]
