# Generated by Django 5.0 on 2025-01-01 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0029_researchassistant_can_acquire_funding_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coinvestigator',
            name='can_acquire_funding',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coinvestigator',
            name='can_approach_participants',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coinvestigator',
            name='can_collect_data',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coinvestigator',
            name='can_conceptualize_methodology',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coinvestigator',
            name='can_consent_participants',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coinvestigator',
            name='can_identify_participants',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coinvestigator',
            name='can_validate_analyze_data',
            field=models.BooleanField(default=False),
        ),
    ]
